version: '3'

services:
  xray:
    logging:
      options:
        max-size: 10m
    container_name: xray
    image: ghcr.io/xtls/xray-core:24.11.5-ls
    
  wireguard:
    logging:
      options:
        max-size: 10m
    container_name: wireguard
    image: ghcr.io/wg-easy/wg-easy
    environment:
      - WG_HOST=${WG_HOST}
      - PASSWORD=${WG_PASSWORD}
      - LANG=ru
      - UI_TRAFFIC_STATS=true
      #- WG_ALLOWED_IPS=${WG_ALLOWED_IPS}
    volumes:
      - ~/.wg-easy:/etc/wireguard
    ports:
      - 51820:51820/udp
      - 51821:51821/tcp
    cap_add: 
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  shadowsocks:
    logging:
      options:
        max-size: 10m
    container_name: shadowsocks
    image: ghcr.io/shadowsocks/ssserver-rust
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/shadowsocks-rust/config.json
        {
          "server": "0.0.0.0",
          "server_port": 8388,
          "password": "${SHADOWSOCKS_PASSWORD}",
          "method": "aes-256-gcm",
        }
        EOF
        ssserver --log-without-time -a nobody -c /etc/shadowsocks-rust/config.json
    ports:
      - 8388:8388
    restart: unless-stopped

  torrserver:
    logging:
      options:
        max-size: 10m
    image: ghcr.io/yourok/torrserver
    container_name: torrserver
    environment:
      - TS_PORT=5665
      - TS_DONTKILL=1
      - TS_HTTPAUTH=1
      - TS_CONF_PATH=/opt/ts/config
      - TS_TORR_DIR=/opt/ts/torrents
    volumes:
      - './CACHE:/opt/ts/torrents'
      - './CONFIG:/opt/ts/config'
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /opt/ts/config/accs.db
        {
          "admin": "${TS_PASSWORD}"
        }
        EOF
        /docker-entrypoint.sh
    ports:
      - '5665:5665'
    restart: unless-stopped
